### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by girishramnani** [pypyjs/pypyjs.github.io#13]

**Comment by jedie** [comment]
Think, as in README: 

> All code is available under the MIT License.

@rfk isn't it?

**Comment by girishramnani** [comment]
thats awesome. Thanks

**Comment by rfk** [comment]
Yes, all the original code here is under MIT license, and so is the core PyPy code.  There are some third-party js modules reproduced under their own open-source licenses which I don't recall right now, but everything is free to re-use under pretty standard non-copyleft open-source licenses.
