### ISSUE TITLE
Invalid SSL certificate (pypyjs.org)

### ISSUE THREAD

**Issue by ncouture** [pypyjs/pypyjs.github.io#18]
FYI:

> Attackers might be trying to steal your information from pypyjs.org (for example, passwords, messages, or credit cards). Learn more
> NET::ERR_CERT_COMMON_NAME_INVALID
> Subject: *.github.com
> 
> Issuer: DigiCert SHA2 High Assurance Server CA
> 
> Expires on: Apr 7, 2020
> 
> Current date: May 19, 2018

**Comment by rfk** [comment]
Thanks!  I poke a few buttons in the github pages UI to generate a proper certificate and this should be working now.
